version: "3.9"

services:
  db:
    image: postgres
    container_name: lenslocked_db
    restart: always
    environment:
      POSTGRES_USER: baloo
      POSTGRES_PASSWORD: junglebook
      POSTGRES_DB: lenslocked
    ports:
      - "5432:5432"
